# Generated by Django 4.1.3 on 2022-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='country',
            field=models.CharField(choices=[('default', '나라 선택하기'), ('ko', '한국'), ('usa', '미국'), ('japan', '일본')], default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='pet_friendly',
            field=models.BooleanField(default=True, help_text='반려동물 출입여부'),
        ),
    ]
