# Generated by Django 4.1.3 on 2022-11-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_at',
            field=models.TimeField(help_text='영업 종료 시간'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_at',
            field=models.TimeField(help_text='영업 시작 시간'),
        ),
    ]
