# Generated by Django 4.1.3 on 2022-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_alter_video_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
