# Generated by Django 4.1.5 on 2023-01-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, help_text='프로필 사진을 추가 해보세요', null=True, verbose_name='프로필 사진'),
        ),
    ]
