# Generated by Django 4.1.3 on 2022-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='하루 이용 금액')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=150)),
                ('pets_allowed', models.BooleanField(default=True, help_text='반려동물 동반 가능하면 체크하세요.', verbose_name='반려동물 동반 가능 여부')),
            ],
        ),
    ]
